name: darkside # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0-SNAPSHOT' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  Darkside is an application that will help you manipulate environment variables.
  You will choose the file you want to manipulate and darkside will help you to put in the path, delete, change or create a variable.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
apps:
  darkside:
    command: darkside
    plugs:
      - desktop
      - home
parts:
  darkside:
    # See 'snapcraft plugins'
    plugin: nil
    source: .
    stage-packages:
      - bash